# https://xdaforums.com/t/dev-script-android-kernel-actions-easily-create-an-environment-and-build-android-kernels-with-github-action.4301481/
name: "Build kernel"
on:
  push:
  workflow_dispatch: # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build kernel"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout kernel source" # Clone the kernel source.
        uses: actions/checkout@v2
      - name: Make as safe-directory
        run: |
          git config --global --add safe.directory /github/workspace
      - name: "Android kernel build" # Build kernel with lemniskett/android-kernel-actions.
        uses: lemniskett/android-kernel-actions@master
        with:
          arch: arm64 # Specify arch
          compiler: clang/15/binutils # Specify toolchain to use
          defconfig: camellia_defconfig # Specify defconfig to use
          image: kernel.gz-dtb # Specify final build file
      - name: Release build
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.build.outputs.outfile }}
          token: ${{ secrets.GITHUB_TOKEN }}
